### ISSUE TITLE
AccessViolationException on Windows 11

### ISSUE THREAD

**Issue by LAB02-Admin** [Willy-Kimura/HotkeyListener#21]
I've been using your nuget for a while on W10, works really great, thanks for sharing :) 

Recently I made the switch to W11, and now when using the same code, I get the following exception:

```
[MAIN] AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at MS.Internal.Automation.UiaCoreApi.RawTextRange_GetText(SafeTextRangeHandle hobj, Int32 maxLength, String& result)
   at System.Windows.Automation.Text.TextPatternRange.GetText(Int32 maxLength)
   at WK.Libraries.HotkeyListenerNS.Helpers.TextSelectionReader.<>c.<GetTextFromAutomationElement>b__5_0(TextPatternRange r)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at WK.Libraries.HotkeyListenerNS.Helpers.TextSelectionReader.GetTextFromAutomationElement()
   at WK.Libraries.HotkeyListenerNS.Helpers.TextSelectionReader.<.ctor>b__0_0()
   at WK.Libraries.HotkeyListenerNS.Helpers.TextSelectionReader.TryGetSelectedTextFromActiveControl()
   at WK.Libraries.HotkeyListenerNS.Helpers.SourceAttributes.GetSelection()
   at WK.Libraries.HotkeyListenerNS.Helpers.HotkeyHandle.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Program.Main()
```

It looks like the **TextSelectionReader** is causing a crash, perhaps it's breaking some security measures. 

Do you have the time to look into this, or could you give me some pointers on how to remove/disable the TextSelectionReader from your source?

Thanks!

**Comment by LAB02-Admin** [comment]
Update: I've removed TextSelectionReader.cs and its references, and changed SourceAttributes.GetSelection() to just return an empty string. This resolved the crash.

**Comment by Willy-Kimura** [comment]
Thank you for reporting this. I'll be sure to look into it.

In the meantime, checkout [this SO thread](https://stackoverflow.com/questions/4074585/attempted-to-read-or-write-protected-memory-this-is-often-an-indication-that-ot).

**Comment by LAB02-Admin** [comment]
Yea it's probably a x86/x64 thing. Not an issue anymore when not looking into the target application through GetSelection(), perhaps make it optional/configurable?

**Comment by Willy-Kimura** [comment]
Sure, I can work on that.

**Comment by thomasklemenc** [comment]
Can confirm this issue on Win 11 22621.1848
My program using the HKL class crashes when the hotkey is pressed while certain programs are in focus. (MS Edge, Outlook are two examples)

[This function ](https://github.com/Willy-Kimura/HotkeyListener/blob/62f0687cef94ca63e4e99d21a2796e7bdf5d4c47/HotkeyListener/Helpers/Internal/TextSelectionReader.cs#L198)is what crashes the application with a `System.AccessViolationException` as it is trying to access secure memory

commenting out this function [here](https://github.com/Willy-Kimura/HotkeyListener/blob/62f0687cef94ca63e4e99d21a2796e7bdf5d4c47/HotkeyListener/Helpers/Internal/TextSelectionReader.cs#L61C3-L61C3) works for me as a workaround
