### ISSUE TITLE
Compile Error in VS 2019

### ISSUE THREAD

**Issue by BennoB666** [Willy-Kimura/HotkeyListener#9]
After cloning you git repository and compile i get an error "System.ArgumentException
  HResult=0x80070057
  Nachricht = Die Assembly "C:\Users\XXX\source\repos\HotkeyListener\HotkeyListener\obj\Debug\HotkeyListener.dll" enthält keine UserControl-Typen.
  Quelle = UserControlTestContainer
  Stapelüberwachung:
   at Microsoft.VisualStudio.Tools.UserControlTestContainer.UserControlTestContainer_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
"

**Comment by BennoB666** [comment]
SOLVED!! 
Make the HotkeyListener.Demo as Startproject.

**Comment by Willy-Kimura** [comment]
That easy!
